#include <stdio.h>
#include <CNemIDBoringSSL_x509.h>
#include <CNemIDBoringSSL_asn1.h>
#include <CNemIDBoringSSL_asn1t.h>
#include "include/c_nemid_ssl.h"

ASN1_SEQUENCE(OCSP_SIGNATURE) = {
    ASN1_EMBED(OCSP_SIGNATURE, signatureAlgorithm, X509_ALGOR),
    ASN1_SIMPLE(OCSP_SIGNATURE, signature, ASN1_BIT_STRING),
    ASN1_EXP_SEQUENCE_OF_OPT(OCSP_SIGNATURE, certs, X509, 0)
} ASN1_SEQUENCE_END(OCSP_SIGNATURE)

IMPLEMENT_ASN1_FUNCTIONS(OCSP_SIGNATURE)

ASN1_SEQUENCE(OCSP_CERTID) = {
    ASN1_EMBED(OCSP_CERTID, hashAlgorithm, X509_ALGOR),
    ASN1_EMBED(OCSP_CERTID, issuerNameHash, ASN1_OCTET_STRING),
    ASN1_EMBED(OCSP_CERTID, issuerKeyHash, ASN1_OCTET_STRING),
    ASN1_EMBED(OCSP_CERTID, serialNumber, ASN1_INTEGER)
} ASN1_SEQUENCE_END(OCSP_CERTID)

IMPLEMENT_ASN1_FUNCTIONS(OCSP_CERTID)

ASN1_SEQUENCE(OCSP_ONEREQ) = {
    ASN1_SIMPLE(OCSP_ONEREQ, reqCert, OCSP_CERTID),
    ASN1_EXP_SEQUENCE_OF_OPT(OCSP_ONEREQ, singleRequestExtensions, X509_EXTENSION, 0)
} ASN1_SEQUENCE_END(OCSP_ONEREQ)

IMPLEMENT_ASN1_FUNCTIONS(OCSP_ONEREQ)

ASN1_SEQUENCE(OCSP_REQINFO) = {
    ASN1_EXP_OPT(OCSP_REQINFO, version, ASN1_INTEGER, 0),
    ASN1_EXP_OPT(OCSP_REQINFO, requestorName, GENERAL_NAME, 1),
    ASN1_SEQUENCE_OF(OCSP_REQINFO, requestList, OCSP_ONEREQ),
    ASN1_EXP_SEQUENCE_OF_OPT(OCSP_REQINFO, requestExtensions, X509_EXTENSION, 2)
} ASN1_SEQUENCE_END(OCSP_REQINFO)

IMPLEMENT_ASN1_FUNCTIONS(OCSP_REQINFO)

ASN1_SEQUENCE(OCSP_REQUEST) = {
    ASN1_EMBED(OCSP_REQUEST, tbsRequest, OCSP_REQINFO),
    ASN1_EXP_OPT(OCSP_REQUEST, optionalSignature, OCSP_SIGNATURE, 0)
} ASN1_SEQUENCE_END(OCSP_REQUEST)

IMPLEMENT_ASN1_FUNCTIONS(OCSP_REQUEST)

